port: 21122
framework: jasmine
serve_files: 
  - 'bower_components/angular-1.2.0-rc.2/angular.js'
  - '.tmp/src/*.js'
  - 'bower_components/angular-mocks-1.2.0-rc.2/angular-mocks.js'
  - '.tmp/tests/*.js'
