before_tests: "./scripts/before_tests"
on_exit: "rm -r .tmp/"
src_files:
  - "src/*.coffee"
  - "tests/*.coffee"

serve_files: 
  - 'bower_components/angular-1.2.0-rc.3/angular.js'
  - '.tmp/src/*.js'
  - 'bower_components/angular-mocks-1.2.0-rc.3/angular-mocks.js'
  - '.tmp/tests/*.js'

launchers: 
  Angular 1.0.3:
    command: 'testem ci --file .testem-angular-1.0.3.yml'
    protocol: 'tap'
  Angular 1.0.4:
    command: 'testem ci --file .testem-angular-1.0.4.yml'
    protocol: 'tap'
  Angular 1.0.5:
    command: 'testem ci --file .testem-angular-1.0.5.yml'
    protocol: 'tap'
  Angular 1.0.6:
    command: 'testem ci --file .testem-angular-1.0.6.yml'
    protocol: 'tap'
  Angular 1.0.7:
    command: 'testem ci --file .testem-angular-1.0.7.yml'
    protocol: 'tap'
  Angular 1.0.8:
    command: 'testem ci --file .testem-angular-1.0.8.yml'
    protocol: 'tap'
  Angular 1.2.0-rc.1:
    command: 'testem ci --file .testem-angular-1.2.0-rc.1.yml'
    protocol: 'tap'
  Angular 1.2.0-rc.2:
    command: 'testem ci --file .testem-angular-1.2.0-rc.2.yml'
    protocol: 'tap'
  Angular 1.2.0-rc.3:
    command: 'testem ci --file .testem-angular-1.2.0-rc.3.yml'
    protocol: 'tap'

launch_in_ci: 
  - Angular 1.0.3
  - Angular 1.0.4
  - Angular 1.0.5
  - Angular 1.0.6
  - Angular 1.0.7
  - Angular 1.0.8
  - Angular 1.2.0-rc.1
  - Angular 1.2.0-rc.2
  - Angular 1.2.0-rc.3

launch_in_dev: []
