port: 21121
framework: jasmine
serve_files: 
  - 'bower_components/angular-1.2.0-rc.1/angular.js'
  - '.tmp/src/*.js'
  - 'bower_components/angular-mocks-1.2.0-rc.1/angular-mocks.js'
  - '.tmp/tests/*.js'
