language: node_js
node_js:
  - 0.10
env:
  - DISPLAY=:99.0
before_script:
  - npm install bower
  - npm install -g codeclimate-test-reporter
  - ./node_modules/.bin/bower install --dev
after_script:
  - cat lcov.info | codeclimate
