language: node_js
node_js:
  - 0.10
env:
  - DISPLAY=:99.0
before_script:
  - npm install bower
  - ./node_modules/.bin/bower install --dev
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - ./node_modules/.bin/testem launchers
